In [14]:
import numpy as np
import matplotlib
import pandas as pd
import math

In [2]:
darkPath = '/home/marteswong/CCD/CCD dark/'
dark_bias = 'bias_0_230915-143930.dat'
dark_dark = 'dark_0_230915-143346.dat'


data_df = pd.read_csv(darkPath + dark_dark, delimiter=' ')
data_array = np.array(data_df)
print(data_array.shape)

(959, 1281)


In [3]:
#Convert the value from hex to dec
data_dec = np.zeros(data_array.shape)

for i in range(len(data_array)):
    for j in range(len(data_array[i])-1):
        t = data_array[i][j]
        d = int(str(t), base=16)
        data_dec[i][j] = d

# t = 'A3'
# d = int(t, base=16)
# print('Decimal :', d)


In [4]:
print(data_dec[430:530, 590:690])

[[16.  0.  0. ...  0.  0.  2.]
 [ 0.  0. 13. ... 17.  0.  1.]
 [ 0. 13.  3. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  1. 17.  0.]
 [ 0.  0. 18. ... 25.  6.  0.]
 [ 0.  0. 14. ... 96.  0. 67.]]


In [5]:
test1 = data_dec[430:530, 590:690]   # 6289
test2 = data_dec[410:510, 570:670]   # 6259
test3 = data_dec[450:550, 610:710]   # 6239

print("Count 1:" + str(np.unique(test1, return_counts=True)))
print()
print("Count 2:" + str(np.unique(test2, return_counts=True)))
print()
print("Count 3:" + str(np.unique(test3, return_counts=True)))

# Choose the first one
dark_roi = data_dec[430:530, 590:690]

Count 1:(array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  78.,  79.,  81.,
        82.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  94.,  96.,
        97., 100., 104., 111., 113., 114., 115., 120., 125., 138., 143.,
       147., 148., 153., 157., 158., 206., 238.]), array([6289,  426,  413,  265,  299,  247,  204,  148,  169,  133,  129,
        107,   88,   77,   66,   67,   61,   59,   52,   51,   45,   37,
         27,   43,   25,   33,   28,   23,   14,   19,   16,   17,   23,
         24,   14,   10,   17,   12,    9,   12,    7,   12,   1

### **Choose [430:530, 590:690] as the subset, i.e. the Region of Interest(ROI)**

In [6]:
data_df = pd.read_csv(darkPath + dark_bias, delimiter=' ')
bias_array = np.array(data_df)[430:530, 590:690]
# there are only 0.0s and 1.0s in bias_array(automatic conversion? idk), therefore no need to convert to decimal number)
# print("Count bias:" + str(np.unique(bias_array, return_counts=True)))

In [11]:
# Compute the dark count in counts per second(as I haven't got the system gain of the CCD to convert to electrons/second)
C_b = np.mean(bias_array)
C_d = np.mean(dark_roi)
result = (C_d - C_b)/60
print("{:.5f}".format(C_b))
print("{:.5f}".format(C_d))
print("Result(count per second) = " + str(result))    # 0.07429833333333333

0.00140
4.45930
Result(count per second) = 0.07429833333333333


In [9]:
print(dark_roi[47, 49])
print(dark_roi[51][50])
# Choose this pixel as THE pixel in exp 3c

0.0
0.0


In [10]:
# Compute the dark count in electrons per second
gain = 34.113
result2 = (C_d - C_b)/60 * gain
print("Result(electrons per second) = " + str(result2))    # 2.534539045

Result(electrons per second) = 2.534539045


In [12]:
# Compute the std of bias and bias-subtracted dark frame
dC_b = np.std(bias_array)   
dC_d = np.std(dark_roi)     
print(dC_b)
print(dC_d)

0.037390373092548834
11.528058965411306


In [15]:
# Compute the std of the system gain and the dark count
dC = math.sqrt((dC_b**2)+(dC_d**2))
print(dC)

11.528119601652302


In [16]:
print(C_d - C_b)

4.4578999999999995
